export const dynamic = 'force-dynamic'
import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { supabaseAdmin } from '@/lib/supabase-admin'

const NEW_TOOLS = [
  // AI AGENTS
  { name: 'OpenClaw', slug: 'openclaw', category: 'AI Agents', description: 'The viral open-source personal AI agent with 145,000+ GitHub stars. Runs locally on your machine, connects AI models to your files, apps, and messaging platforms like WhatsApp and Telegram. Executes tasks autonomously — manage emails, browse the web, automate workflows — without sending data to the cloud. The closest thing to JARVIS for regular people.', website_url: 'https://openclaw.ai', pricing: 'Free (bring your own API key)', experience_level: 'Intermediate', tags: ['agent', 'open-source', 'automation', 'local', 'self-hosted'] },
  { name: 'Devin', slug: 'devin', category: 'AI Agents', description: 'The first fully autonomous AI software engineer by Cognition AI. Devin plans, codes, tests, and deploys software end-to-end with a 67% PR merge rate on defined tasks. Operates in its own sandboxed environment with a browser, terminal, and code editor.', website_url: 'https://cognition.ai', pricing: '$500/month', experience_level: 'Advanced', tags: ['agent', 'coding', 'autonomous', 'engineering', 'enterprise'] },
  { name: 'Manus', slug: 'manus', category: 'AI Agents', description: 'General-purpose autonomous AI agent that went viral in 2025. Manus independently completes complex multi-step tasks by browsing the web, writing code, analyzing data, and creating files. Designed to handle entire projects end-to-end, not just answer questions.', website_url: 'https://manus.im', pricing: 'Waitlist / Paid', experience_level: 'Beginner', tags: ['agent', 'autonomous', 'general-purpose', 'research', 'viral'] },
  { name: 'AutoGPT', slug: 'autogpt', category: 'AI Agents', description: 'The open-source AI agent that pioneered the autonomous AI movement. AutoGPT chains model calls together to complete long-horizon tasks with minimal human involvement. The foundational project that inspired hundreds of successors and introduced the world to AI agents.', website_url: 'https://agpt.co', pricing: 'Free / Cloud version available', experience_level: 'Intermediate', tags: ['agent', 'open-source', 'automation', 'pioneer', 'gpt'] },
  { name: 'Lindy', slug: 'lindy', category: 'AI Agents', description: 'No-code AI agent builder for automating business workflows. Create agents that handle emails, schedule meetings, manage CRM entries, and connect to 3,000+ apps. Trigger-based automation powered by AI — no programming required.', website_url: 'https://lindy.ai', pricing: 'Free tier / Paid from $49/month', experience_level: 'Beginner', tags: ['agent', 'automation', 'no-code', 'workflow', 'business'] },
  { name: 'CrewAI', slug: 'crewai', category: 'AI Agents', description: 'Open-source framework for orchestrating teams of AI agents that collaborate on complex tasks. Each agent has a defined role and goal, working together like a real crew. The leading framework for developers building multi-agent pipelines.', website_url: 'https://crewai.com', pricing: 'Free (open-source)', experience_level: 'Advanced', tags: ['agent', 'framework', 'multi-agent', 'open-source', 'orchestration'] },
  { name: 'n8n', slug: 'n8n', category: 'AI Agents', description: 'Open-source workflow automation with native AI agent capabilities. Connect 400+ apps and add AI steps to automate complex business processes. Self-hostable with a visual drag-and-drop builder — the developer-friendly, data-sovereign alternative to Zapier.', website_url: 'https://n8n.io', pricing: 'Free self-hosted / Cloud from $24/month', experience_level: 'Intermediate', tags: ['automation', 'workflow', 'open-source', 'self-hosted', 'no-code'] },
  // AI MODELS
  { name: 'GPT-4o', slug: 'gpt-4o', category: 'AI Models', description: "OpenAI flagship multimodal model that sees, hears, and responds in real time. GPT-4o processes text, images, audio, and video natively and powers ChatGPT Plus. One of the most capable general-purpose AI models available.", website_url: 'https://openai.com/gpt-4o', pricing: 'Free in ChatGPT / API pay-per-use', experience_level: 'Beginner', tags: ['model', 'multimodal', 'openai', 'vision', 'audio'] },
  { name: 'GPT-5', slug: 'gpt-5', category: 'AI Models', description: "OpenAI's most powerful model with dynamic reasoning — it chooses how deeply to think based on complexity. GPT-5 combines reasoning, creativity, and knowledge at unprecedented scale. Top choice for complex analysis, writing, and coding.", website_url: 'https://openai.com', pricing: 'ChatGPT Pro / API pay-per-use', experience_level: 'Beginner', tags: ['model', 'openai', 'reasoning', 'frontier', 'powerful'] },
  { name: 'DeepSeek R1', slug: 'deepseek-r1', category: 'AI Models', description: "China breakthrough open-source AI that stunned the industry with frontier-level performance at a fraction of the cost. DeepSeek-R1 matches GPT-4 on reasoning benchmarks while being freely downloadable and self-hostable. Sparked a global AI cost rethink in early 2025.", website_url: 'https://deepseek.com', pricing: 'Free open-source / API from $0.14/million tokens', experience_level: 'Intermediate', tags: ['model', 'open-source', 'chinese', 'reasoning', 'affordable'] },
  { name: 'Llama 4', slug: 'llama-4', category: 'AI Models', description: "Meta open-source frontier model family with a 10 million token context window — the largest ever. Free to download, run locally, and fine-tune. With Meta open weights, anyone can build with Llama for free with no API key required.", website_url: 'https://llama.meta.com', pricing: 'Free (open weights)', experience_level: 'Intermediate', tags: ['model', 'meta', 'open-source', 'open-weights', 'local'] },
  { name: 'Mistral Large', slug: 'mistral-large', category: 'AI Models', description: "European open-source AI model that competes with GPT-4 at lower cost. Mistral Large excels at reasoning, multilingual tasks, and code generation. Strong focus on European data sovereignty and on-premise deployment for regulated industries.", website_url: 'https://mistral.ai', pricing: 'API from €0.007/1K tokens', experience_level: 'Intermediate', tags: ['model', 'european', 'open-source', 'efficient', 'multilingual'] },
  { name: 'Gemini 3 Pro', slug: 'gemini-3-pro', category: 'AI Models', description: "Google most capable multimodal model with a 2 million token context window. Gemini 3 Pro analyzes long documents, videos, and codebases and integrates directly into Google Workspace, Search, and Android.", website_url: 'https://gemini.google.com', pricing: 'Free / Google One AI Premium $20/month', experience_level: 'Beginner', tags: ['model', 'google', 'multimodal', 'long-context', 'frontier'] },
  // CODING & DEV
  { name: 'Claude Code', slug: 'claude-code', category: 'Coding & Dev', description: "Anthropic terminal-based AI coding agent generating $2.5B+ ARR. Reads your entire codebase, writes and edits files, runs tests, and fixes bugs autonomously. Claude Opus 4.5 scored 80.9% on SWE-bench — the highest of any model. The go-to tool when other tools fail.", website_url: 'https://claude.ai/code', pricing: 'Included with Claude Pro $20/month', experience_level: 'Intermediate', tags: ['coding', 'agent', 'terminal', 'anthropic', 'autonomous'] },
  { name: 'Windsurf', slug: 'windsurf', category: 'Coding & Dev', description: "AI-first code editor by Codeium, ranked #1 in developer power rankings March 2026. Cascade AI agent handles multi-file edits with live preview. Arena Mode compares models side-by-side. Best value agentic IDE at $15/month.", website_url: 'https://codeium.com/windsurf', pricing: 'Free tier / Pro $15/month', experience_level: 'Intermediate', tags: ['coding', 'ide', 'agent', 'editor', 'codeium'] },
  { name: 'Bolt.new', slug: 'bolt-new', category: 'Coding & Dev', description: 'Build full-stack web apps from a text prompt, entirely in your browser. WebContainers run Node.js locally with no setup. Go from idea to deployed app in minutes. Made by StackBlitz.', website_url: 'https://bolt.new', pricing: 'Free tier / Pro $20/month', experience_level: 'Beginner', tags: ['app-builder', 'no-code', 'browser', 'full-stack', 'rapid-prototyping'] },
  { name: 'v0 by Vercel', slug: 'v0-vercel', category: 'Coding & Dev', description: 'Generate production-ready React UI components from text or screenshots. v0 outputs clean Tailwind + shadcn/ui code you can copy directly into your project. Skip the boilerplate and jump straight to building.', website_url: 'https://v0.dev', pricing: 'Free tier / Pro $20/month', experience_level: 'Beginner', tags: ['ui', 'react', 'components', 'design', 'vercel'] },
  { name: 'Replit', slug: 'replit', category: 'Coding & Dev', description: 'Browser-based IDE with AI built in. Replit AI builds entire apps from a description, debugs code, and explains concepts. Used by 35 million developers for learning, prototyping, and shipping. The easiest way to code with no installation.', website_url: 'https://replit.com', pricing: 'Free tier / Core $15/month', experience_level: 'Beginner', tags: ['ide', 'browser', 'learning', 'prototyping', 'collaboration'] },
  { name: 'Cline', slug: 'cline', category: 'Coding & Dev', description: 'Open-source AI coding agent for VS Code with 5 million installs and zero markup on API costs. Supports 100+ LLM providers. Autonomous multi-file editing with approval-based execution — you stay in control.', website_url: 'https://cline.bot', pricing: 'Free (bring your own API key)', experience_level: 'Intermediate', tags: ['coding', 'vscode', 'open-source', 'agent', 'byok'] },
  { name: 'Aider', slug: 'aider', category: 'Coding & Dev', description: 'Git-native AI coding assistant for your terminal. Aider understands your entire repo, makes multi-file edits, and automatically commits changes to git. A favorite for developers who prefer command-line workflows.', website_url: 'https://aider.chat', pricing: 'Free (open-source, bring your own API key)', experience_level: 'Advanced', tags: ['coding', 'terminal', 'git', 'open-source', 'byok'] },
  { name: 'Antigravity', slug: 'antigravity', category: 'Coding & Dev', description: 'Free AI coding agent ranked #2 in March 2026 developer power rankings. Supports Claude Opus 4.5, Gemini 3 Flash, GPT-OSS, and more. Multi-agent orchestration with integrated Chrome browser automation — all free during preview.', website_url: 'https://antigravity.dev', pricing: 'Free during preview', experience_level: 'Intermediate', tags: ['coding', 'agent', 'free', 'multi-model', 'browser-automation'] },
  { name: 'Tabnine', slug: 'tabnine', category: 'Coding & Dev', description: 'AI code completion with enterprise-grade privacy. Tabnine offers air-gapped model deployment so code never leaves your infrastructure. All major IDEs supported, 30+ programming languages. The choice for security-conscious teams.', website_url: 'https://tabnine.com', pricing: 'Free tier / Pro $9/month / Enterprise $39/month', experience_level: 'Beginner', tags: ['coding', 'autocomplete', 'privacy', 'enterprise', 'ide'] },
  { name: 'OpenCode', slug: 'opencode', category: 'Coding & Dev', description: 'Open-source terminal coding agent with 95,000+ GitHub stars — more than Claude Code. Supports 75+ LLM providers, plan-first development with editable task plans, and approval-based execution. Used by 2.5 million developers monthly.', website_url: 'https://opencode.ai', pricing: 'Free (open-source)', experience_level: 'Intermediate', tags: ['coding', 'terminal', 'open-source', 'agent', 'plan-first'] },
  // APP BUILDERS
  { name: 'Bubble', slug: 'bubble', category: 'App Builders', description: 'The leading no-code platform for building fully functional web apps without writing code. Bubble visual editor now integrates AI to generate app logic and database structures. 3 million+ makers have launched real businesses on it.', website_url: 'https://bubble.io', pricing: 'Free tier / Starter $29/month', experience_level: 'Beginner', tags: ['no-code', 'app-builder', 'visual', 'web-app', 'database'] },
  { name: 'Webflow', slug: 'webflow', category: 'App Builders', description: 'Visual web design platform that generates production-quality HTML, CSS, and JavaScript. Webflow AI writes copy, generates layouts, and optimizes sites. Used by professional designers and agencies for pixel-perfect websites.', website_url: 'https://webflow.com', pricing: 'Free tier / Basic $18/month', experience_level: 'Intermediate', tags: ['no-code', 'web-design', 'cms', 'visual', 'professional'] },
  { name: 'Framer', slug: 'framer', category: 'App Builders', description: 'AI-powered website builder that turns text into fully designed responsive websites. Framer AI generates complete pages with copy, images, and layout from a single prompt. Loved by product designers for fast iteration.', website_url: 'https://framer.com', pricing: 'Free tier / Mini $10/month', experience_level: 'Beginner', tags: ['no-code', 'website', 'design', 'ai-generated', 'prototype'] },
  { name: 'Dify', slug: 'dify', category: 'App Builders', description: 'Open-source platform for building AI applications with a visual workflow builder. Dify supports RAG pipelines, multi-agent systems, and custom chatbots with all major LLM providers. Self-hostable with 60,000+ GitHub stars.', website_url: 'https://dify.ai', pricing: 'Free self-hosted / Cloud from $59/month', experience_level: 'Intermediate', tags: ['agent', 'open-source', 'rag', 'workflow', 'llm'] },
  // SEARCH & RESEARCH
  { name: 'Perplexity Pro', slug: 'perplexity-pro', category: 'Search & Research', description: 'AI-powered search engine that cites every source. Perplexity Pro adds advanced models, unlimited file uploads, and real-time web search. Unlike ChatGPT, every answer includes citations you can verify. The internet finally made accurate.', website_url: 'https://perplexity.ai', pricing: 'Free tier / Pro $20/month', experience_level: 'Beginner', tags: ['search', 'research', 'citations', 'realtime', 'web'] },
  { name: 'Consensus', slug: 'consensus', category: 'Search & Research', description: 'AI search for scientific research. Consensus searches 200 million academic papers and extracts key findings with direct citations. Perfect for fact-checking health claims, business decisions, and policy research with real evidence.', website_url: 'https://consensus.app', pricing: 'Free tier / Premium $9.99/month', experience_level: 'Beginner', tags: ['search', 'research', 'academic', 'science', 'citations'] },
  { name: 'Exa', slug: 'exa', category: 'Search & Research', description: 'AI-native search engine built for developers. Unlike keyword search, Exa understands meaning and returns semantically relevant results. Powerful API for building AI applications that need intelligent web search.', website_url: 'https://exa.ai', pricing: 'Free tier / API from $1/1000 searches', experience_level: 'Intermediate', tags: ['search', 'api', 'semantic', 'developer', 'research'] },
  // IMAGE GENERATION
  { name: 'Flux Pro', slug: 'flux-pro', category: 'Image Generation', description: 'The new industry standard for photorealistic image generation from Black Forest Labs. Flux Pro produces stunning images with accurate text rendering — long a weakness of AI image tools. Available via Replicate, fal.ai, and other platforms.', website_url: 'https://blackforestlabs.ai', pricing: 'API from $0.055/image', experience_level: 'Intermediate', tags: ['image', 'photorealistic', 'text-rendering', 'api', 'model'] },
  { name: 'Stable Diffusion', slug: 'stable-diffusion', category: 'Image Generation', description: 'The original open-source image generation model. Runs locally on your GPU for free — no subscriptions, no content restrictions. The foundation for the Automatic1111 and ComfyUI ecosystem with hundreds of fine-tuned models.', website_url: 'https://stability.ai', pricing: 'Free (open-source)', experience_level: 'Advanced', tags: ['image', 'open-source', 'local', 'free', 'customizable'] },
  { name: 'Krea AI', slug: 'krea-ai', category: 'Image Generation', description: 'Real-time AI image generation — draw a sketch and watch it become photorealistic instantly. Krea features AI upscaling, video generation, and a real-time canvas. Beloved by designers who want immediate visual feedback.', website_url: 'https://krea.ai', pricing: 'Free tier / Pro $24/month', experience_level: 'Beginner', tags: ['image', 'real-time', 'upscaling', 'video', 'creative'] },
  { name: 'Ideogram 2.0', slug: 'ideogram-2', category: 'Image Generation', description: 'The best AI tool for images with text. Ideogram 2.0 accurately generates legible text, logos, and typography in images — something other models still fail at. Essential for social media graphics, thumbnails, and branded content.', website_url: 'https://ideogram.ai', pricing: 'Free (25/day) / Basic $7/month', experience_level: 'Beginner', tags: ['image', 'text-rendering', 'logos', 'typography', 'social-media'] },
  // VIDEO & AUDIO
  { name: 'Kling AI', slug: 'kling-ai', category: 'Video & Audio', description: "Kuaishou video generation model with photorealistic output that challenged Sora. Generates high-quality 2-minute videos from text or images with realistic motion physics. Used by filmmakers and creators for B-roll and concept visualization.", website_url: 'https://klingai.com', pricing: 'Free tier / Paid plans', experience_level: 'Beginner', tags: ['video', 'generation', 'photorealistic', 'text-to-video', 'creators'] },
  { name: 'Luma Dream Machine', slug: 'luma-dream-machine', category: 'Video & Audio', description: 'High-quality text-to-video AI from Luma Labs. Creates smooth, physically accurate videos with impressive motion quality. Popular for product demos, visualizations, and short creative films from static images.', website_url: 'https://lumalabs.ai', pricing: 'Free tier / Plus $29.99/month', experience_level: 'Beginner', tags: ['video', 'text-to-video', 'image-to-video', 'motion', 'creative'] },
  { name: 'Suno', slug: 'suno', category: 'Video & Audio', description: 'AI music generation that creates complete songs from text — vocals, instruments, lyrics, and all. Suno v4 produces radio-quality music across any genre in seconds. Used by millions to create jingles, background tracks, and full songs with zero musical experience.', website_url: 'https://suno.com', pricing: 'Free (10 songs/day) / Pro $8/month', experience_level: 'Beginner', tags: ['music', 'audio', 'generation', 'songs', 'creative'] },
  { name: 'Udio', slug: 'udio', category: 'Video & Audio', description: "AI music generator rivaling Suno with exceptional audio quality. Udio produces professional-grade tracks with nuanced instrument separation and emotional depth. Strong for original background music for videos, podcasts, and content.", website_url: 'https://udio.com', pricing: 'Free tier / Standard $10/month', experience_level: 'Beginner', tags: ['music', 'audio', 'generation', 'professional', 'background'] },
  { name: 'Opus Clip', slug: 'opus-clip', category: 'Video & Audio', description: 'Automatically repurpose long videos into short viral clips. Opus Clip finds the most engaging moments in your podcast or YouTube video and creates ready-to-post TikTok, Reels, and Shorts — complete with captions. Saves hours of editing.', website_url: 'https://opus.pro', pricing: 'Free tier / Starter $15/month', experience_level: 'Beginner', tags: ['video', 'repurposing', 'clips', 'social-media', 'creator'] },
  { name: 'Captions', slug: 'captions', category: 'Video & Audio', description: 'AI video creation app for social media creators. Adds animated captions, removes filler words, corrects eye contact, and translates to 28 languages. Used by millions to produce polished content from their phone without a video editor.', website_url: 'https://captions.ai', pricing: 'Free tier / Pro $19.99/month', experience_level: 'Beginner', tags: ['video', 'captions', 'editing', 'translation', 'creator'] },
  { name: 'Adobe Podcast', slug: 'adobe-podcast', category: 'Video & Audio', description: 'AI audio tool that enhances speech quality instantly. Removes background noise and improves any microphone to studio level with one click. Free to use — a game-changer for podcasters, YouTubers, and remote workers on video calls.', website_url: 'https://podcast.adobe.com', pricing: 'Free (beta)', experience_level: 'Beginner', tags: ['audio', 'podcast', 'noise-removal', 'microphone', 'adobe'] },
  // PRODUCTIVITY
  { name: 'Mem', slug: 'mem', category: 'Productivity', description: 'AI-powered note-taking app that organizes itself. No folders, no tags — Mem understands your notes and surfaces relevant information when you need it. Ask questions and get answers from your own knowledge base.', website_url: 'https://mem.ai', pricing: 'Free / Pro $14.99/month', experience_level: 'Beginner', tags: ['notes', 'knowledge-management', 'ai', 'organization', 'search'] },
  { name: 'Taskade', slug: 'taskade', category: 'Productivity', description: 'All-in-one AI productivity platform with tasks, notes, mind maps, and custom AI agents. Build agents that manage projects, generate reports, and automate workflows. Good for small teams wanting AI embedded in project management.', website_url: 'https://taskade.com', pricing: 'Free / Pro $8/month', experience_level: 'Beginner', tags: ['productivity', 'tasks', 'agents', 'team', 'project-management'] },
  { name: 'Gamma', slug: 'gamma-ai', category: 'Productivity', description: 'AI presentation and document builder generating beautiful decks, webpages, and docs from a prompt. Handles design automatically with smart layouts, AI images, and themes. Creates investor-ready presentations in minutes.', website_url: 'https://gamma.app', pricing: 'Free tier / Plus $8/month', experience_level: 'Beginner', tags: ['presentations', 'documents', 'design', 'automated', 'slides'] },
  { name: 'Tome', slug: 'tome', category: 'Productivity', description: 'AI-native presentation tool creating complete decks with AI images, data visualizations, and compelling copy from a prompt. Used for sales pitches, investor decks, and executive briefings by professionals who need polished results fast.', website_url: 'https://tome.app', pricing: 'Free / Pro $16/month', experience_level: 'Beginner', tags: ['presentations', 'slides', 'ai-generated', 'design', 'storytelling'] },
  { name: 'Harvey AI', slug: 'harvey-ai', category: 'Productivity', description: 'AI platform built for lawyers and legal professionals. Harvey drafts contracts, analyzes legal documents, conducts case research, and summarizes filings. Trained on vast legal data and trusted by leading law firms globally.', website_url: 'https://harvey.ai', pricing: 'Enterprise pricing', experience_level: 'Intermediate', tags: ['legal', 'enterprise', 'contracts', 'research', 'compliance'] },
  // WRITING
  { name: 'Quillbot', slug: 'quillbot', category: 'Writing & Content', description: 'AI paraphrasing and grammar tool used by 35 million writers. Rewrites sentences in multiple styles, summarizes long documents, checks grammar, and detects AI-generated content. Essential for students, bloggers, and non-native English speakers.', website_url: 'https://quillbot.com', pricing: 'Free tier / Premium $9.95/month', experience_level: 'Beginner', tags: ['paraphrasing', 'grammar', 'rewriting', 'summarization', 'students'] },
  { name: 'Rytr', slug: 'rytr', category: 'Writing & Content', description: 'Budget-friendly AI writing assistant for blog posts, emails, social captions, and ad copy. Rytr supports 40+ use cases and 30 languages. The practical choice for small business owners who need quality content without premium pricing.', website_url: 'https://rytr.me', pricing: 'Free tier / Saver $9/month', experience_level: 'Beginner', tags: ['writing', 'content', 'affordable', 'small-business', 'multilingual'] },
  { name: 'Character.ai', slug: 'character-ai', category: 'Writing & Content', description: 'Create and chat with AI characters — fictional personas, celebrities, historical figures, and custom creations. Character.ai has 20 million daily active users for creative writing, roleplay, entertainment, and companionship.', website_url: 'https://character.ai', pricing: 'Free / c.ai+ $9.99/month', experience_level: 'Beginner', tags: ['characters', 'creative', 'entertainment', 'roleplay', 'chat'] },
  // DATA & ANALYTICS
  { name: 'Julius AI', slug: 'julius-ai', category: 'Data & Analytics', description: 'AI data analyst that reads spreadsheets, CSV files, and databases and answers questions in plain English. Julius creates charts, runs statistical analysis, and writes Python code for data tasks — no data science experience needed.', website_url: 'https://julius.ai', pricing: 'Free tier / Pro $22/month', experience_level: 'Beginner', tags: ['data', 'analytics', 'spreadsheets', 'visualization', 'no-code'] },
  { name: 'Rows', slug: 'rows', category: 'Data & Analytics', description: 'AI-powered spreadsheet that pulls live data from the web, APIs, and databases. Rows summarizes datasets, generates charts, and answers questions about your data — a smarter alternative to Excel for business intelligence tasks.', website_url: 'https://rows.com', pricing: 'Free tier / Plus $59/month', experience_level: 'Beginner', tags: ['spreadsheet', 'data', 'analytics', 'automation', 'live-data'] },
  // CUSTOMER SERVICE
  { name: 'Intercom Fin', slug: 'intercom-fin', category: 'Customer Service', description: "Intercom AI agent resolving up to 50% of support queries instantly. Trained on your help documentation, Fin handles complex questions accurately and escalates to humans only when needed. Trusted by 25,000+ businesses.", website_url: 'https://intercom.com/fin', pricing: 'Included with Intercom plans', experience_level: 'Beginner', tags: ['customer-service', 'chatbot', 'support', 'automation', 'saas'] },
  { name: 'Tidio', slug: 'tidio', category: 'Customer Service', description: 'Live chat and AI chatbot for ecommerce and small businesses. Tidio Lyro AI answers up to 70% of customer questions automatically in 6 seconds. Easy to install on any website with a free plan covering most small business needs.', website_url: 'https://tidio.com', pricing: 'Free tier / Starter $29/month', experience_level: 'Beginner', tags: ['chat', 'ecommerce', 'customer-service', 'small-business', 'chatbot'] },
  // EDUCATION
  { name: 'Khanmigo', slug: 'khanmigo', category: 'Education', description: "Khan Academy AI tutor powered by GPT-4. Uses Socratic questioning to guide students through problems, helping them truly understand concepts rather than just giving answers. Also helps teachers with lesson planning and student feedback.", website_url: 'https://khanacademy.org/khanmigo', pricing: '$4/month students / Free for teachers', experience_level: 'Beginner', tags: ['education', 'tutoring', 'students', 'k12', 'learning'] },
  { name: 'Duolingo Max', slug: 'duolingo-max', category: 'Education', description: "Duolingo AI-powered language learning with GPT-4 features. Roleplay conversations with AI characters and get personalized feedback on wrong answers. The most engaging way to learn a new language.", website_url: 'https://duolingo.com', pricing: '$29.99/month', experience_level: 'Beginner', tags: ['language-learning', 'education', 'ai-tutor', 'conversation', 'practice'] },
  // HEALTHCARE
  { name: 'Nabla Copilot', slug: 'nabla-copilot', category: 'Healthcare', description: 'AI clinical assistant listening to doctor-patient conversations and automatically generating structured medical notes. Saves physicians 2+ hours per day on documentation. Used by 45,000+ healthcare providers worldwide.', website_url: 'https://nabla.com', pricing: 'Enterprise healthcare pricing', experience_level: 'Beginner', tags: ['healthcare', 'medical', 'notes', 'documentation', 'clinical'] },
]

export async function POST(req: NextRequest) {
  // Accept either cookie auth (admin panel) or Bearer token auth
  const cookieToken = req.cookies.get('admin_token')?.value
  const bearerToken = req.headers.get('authorization')?.replace('Bearer ', '')
  const expected = process.env.ADMIN_TOKEN
  if (!expected || (cookieToken !== expected && bearerToken !== expected)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const { data: existing } = await supabaseAdmin.from('tools').select('slug')
  const existingSlugs = new Set(existing?.map((t: any) => t.slug) || [])

  const toInsert = NEW_TOOLS.filter(t => !existingSlugs.has(t.slug)).map(t => ({
    name: t.name,
    slug: t.slug,
    category: t.category,
    description: t.description,
    website_url: t.website_url,
    pricing: t.pricing,
    experience_level: t.experience_level,
    tags: t.tags,
    status: 'published',
    is_featured: false,
  }))

  if (toInsert.length === 0) {
    return NextResponse.json({ message: 'All tools already exist', skipped: NEW_TOOLS.length })
  }

  const { data, error } = await supabaseAdmin.from('tools').insert(toInsert).select('name')
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({
    success: true,
    inserted: data?.length,
    skipped: NEW_TOOLS.length - (data?.length || 0),
    tools: data?.map((t: any) => t.name),
  })
}
